server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
      stream:
        # binders：配置要绑定的rabbitmq的服务信息
        binders:
          defaultRabbit: # 表示定义的名称，用于于binding整合
            type: rabbit # 消息组件类型
            environment: # 设置rabbitmq的相关的环境配置
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest
        bindings: # 服务的整合处理
          input: # 这个名字是一个通道的名称，表示该应用为消费者
            destination: studyExchange # 指定要使用的Exchange名称
            content-type: application/json # 设置消息类型（设置文本：text/plain）
            binder: defaultRabbit # 设置要绑定的消息服务的具体设置
            #给服务分组：将多个服务放置于同一个group中，就能够保证消息只会被消费一次。
            group: atguiguA
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: receive-8802.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址