server:
  port: 7001

eureka:
  instance:
    #Eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #false表示不注册到注册中心（自己本身就是注册中心）
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖该地址 http://localhost:7001/eureka/ （单机版配置）
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群环境下需要多个注册中心相互守望
      #defaultZone: http://eureka7002.com:7002/eureka/

  server:
    #关闭自我保护机制，保证不可用服务被及时踢除，默认为true，即开启自我保护
    enable-self-preservation: false
    #发送心跳的时间间隔
    eviction-interval-timer-in-ms: 2000
